name: Auto Health Report

#on:
  schedule:
    - cron: '30 23 * * *'  # 任意の時間を入力（mm hhの順でUSTで、入力例では0830JSTに実行される）、入力後は3行目の"#"を削除、00は不可
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Puppeteer and deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libatk-bridge2.0-0 \
          libxss1 \
          libasound2t64
        npm install puppeteer

    - name: Run bot
      run: node Script.js
